# try catch finally,try里有return,finally还执行么?

执行

判断 在 finally 中return ++i
和在  catch 中存在return ++i 的区别